chat:
  bailian:
    key: sk-e242353de1ef4c44b1d6fa3dd7001327

spring:
  zhipu:
    api:
      key: 6fd17261de4445a08c027080b5a5e4fa.h2ravR0gQzwqzHDu   # 你已经换好了，保持不动
      base-url: https://open.bigmodel.cn/api/paas/v4
  application: name:SETSS2026
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://47.109.38.44:3306/setss2026?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
      username: lhz
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

    postgres:
      jdbc-url: jdbc:postgresql://10.135.246.144:5432/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 自动更新表结构（开发环境）
    show-sql: true # 显示SQL语句
    properties:
      hibernate:
        format_sql: true # 格式化SQL输出
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
file:
  upload-dir: D:/setss2026/uploads/manuscripts